resources:
- name: repo
  type: git
  source:
    uri: https://github.com/donfaruco/fly-training.git

jobs:
- name: hello-world-job
  plan:
  - get: repo
    trigger: true
  - task: hello-world-task
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: alpine
      inputs:
      - name: repo
      run:
        path: cat
        args: ["repo/README.md"]
